### ISSUE TITLE
Offset message counts

### ISSUE THREAD

**Issue by sempervictus** [wokket/hl7-mllp-codec#2]
I've got a loop which takes client connections, de-capsulates, logs out the msg ID and loop iteration count, and then re-encapsulates and forwards to another listener component.
When i send 10 messages via `for i in $(seq 0 9); do echo -n -e "\x0b$(cat hl7v2-mllp-sample.txt)\x1c\x0d";done|nc -w1 localhost 20000` the final listener (via `nc -vlp 19999`) which gets data from the forwarder reports 10 messages, but the intermediate forwarder (this code) reports between 6 and 8.
I've put the `println!` inline, tried forcing it to re-transmit data borrowed for the print to force serialization, but no dice, getting wrong counts even though i'm receiving the right messages.
Is this some sort of tokio issue?
The contents of that sample file are:
```
MSH|^~\&|LAB|MYFAC|LAB||201411130917||ORU^R01|3216598|D|2.3|||AL|NE|
PID|1|ABC123DF|AND234DA_PID3|PID_4_ALTID|Patlast^Patfirst^Mid||19670202|F|||4505 21 st^^LAKE COUNTRY^BC^V4V 2S7||222-555-8484|||||MF0050356/15|
PV1|1|O|MYFACSOMPL||||^Xavarie^Sonna^^^^^XAVS|||||||||||REF||SELF|||||||||||||||||||MYFAC||REG|||201411071440||||||||23390^PV1_52Surname^PV1_52Given^H^^Dr^^PV1_52Mnemonic|
ORC|RE|PT103933301.0100|||CM|N|||201411130917|^Kyle^Andra^J.^^^^KYLA||^Xavarie^Sonna^^^^^XAVS|MYFAC|
OBR|1|PT1311:H00001R301.0100|PT1311:H00001R|301.0100^Complete Blood Count (CBC)^00065227^57021-8^CBC \T\ Auto Differential^pCLOCD|R||201411130914|||KYLA||||201411130914||^Xavarie^Sonna^^^^^XAVS||00065227||||201411130915||LAB|F||^^^^^R|^Xavarie^Sonna^^^^^XAVS|
OBX|1|NM|301.0500^White Blood Count (WBC)^00065227^6690-2^Leukocytes^pCLOCD|1|10.1|10\S\9/L|3.1-9.7|H||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|2|NM|301.0600^Red Blood Count (RBC)^00065227^789-8^Erythrocytes^pCLOCD|1|3.2|10\S\12/L|3.7-5.0|L||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|3|NM|301.0700^Hemoglobin (HGB)^00065227^718-7^Hemoglobin^pCLOCD|1|140|g/L|118-151|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|4|NM|301.0900^Hematocrit (HCT)^00065227^4544-3^Hematocrit^pCLOCD|1|0.34|L/L|0.33-0.45|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|5|NM|301.1100^MCV^00065227^787-2^Mean Corpuscular Volume^pCLOCD|1|98.0|fL|84.0-98.0|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|6|NM|301.1300^MCH^00065227^785-6^Mean Corpuscular Hemoglobin^pCLOCD|1|27.0|pg|28.3-33.5|L||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|7|NM|301.1500^MCHC^00065227^786-4^Mean Corpuscular Hemoglobin Concentration^pCLOCD|1|330|g/L|329-352|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|8|NM|301.1700^RDW^00065227^788-0^Erythrocyte Distribution Width^pCLOCD|1|12.0|%|12.0-15.0|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|9|NM|301.1900^Platelets^00065227^777-3^Platelets^pCLOCD|1|125|10\S\9/L|147-375|L||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|10|NM|301.2100^Neutrophils^00065227^751-8^Neutrophils^pCLOCD|1|8.0|10\S\9/L|1.2-6.0|H||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|11|NM|301.2300^Lymphocytes^00065227^731-0^Lymphocytes^pCLOCD|1|1.0|10\S\9/L|0.6-3.1|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|12|NM|301.2500^Monocytes^00065227^742-7^Monocytes^pCLOCD|1|1.0|10\S\9/L|0.1-0.9|H||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|13|NM|301.2700^Eosinophils^00065227^711-2^Eosinophils^pCLOCD|1|0.0|10\S\9/L|0.0-0.5|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
OBX|14|NM|301.2900^Basophils^00065227^704-7^Basophils^pCLOCD|1|0.0|10\S\9/L|0.0-0.2|N||A~S|F|||201411130916|MYFAC^MyFake Hospital^L|
ZDR||^Xavarie^Sonna^^^^^XAVS^^^^^XX^^ATP|
ZPR||
```
I did tried replacing `\n` with `\r` via `for i in $(seq 0 9); do echo -n -e "\x0b$(cat hl7v2-mllp-sample.txt|tr '\n' '\r')\x1c\x0d";done|nc -w1 localhost 20000` but both forwarder runs show the same thing:
```
Listening on 0.0.0.0:20000
Connection opened...
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Connection closed...
Connection opened...
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
Relaying message id 3216598 from 201411130917 original time
```
Any idea how this can happen?

**Comment by sempervictus** [comment]
Ping @wokket (in case GH doesn't)

**Comment by sempervictus** [comment]
Houston, we have a problem. The transport is doing bad things:
```
Got message #1, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #2, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #3, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #4, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #5, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #6, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #7, with 42 lines
Relaying message id 3216598 from 201411130917 original time

Got message #8, with 42 lines
Relaying message id 3216598 from 201411130917 original time

```

**Comment by sempervictus** [comment]
There's a state issue internally somewhere (i think), and not fixed by #1 either :(. Now its starting to double them up on the 5th instead of the 7th message recv'd and that's on the updated dependencies provided with #1.
```
Got message #1, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #2, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #3, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #4, with 21 lines
Relaying message id 3216598 from 201411130917 original time

Got message #5, with 42 lines
Relaying message id 3216598 from 201411130917 original time

Got message #6, with 42 lines
Relaying message id 3216598 from 201411130917 original time

Got message #7, with 42 lines
Relaying message id 3216598 from 201411130917 original time

```

**Comment by sempervictus** [comment]
To quote a formerly IBMR-employed salty as hell architect with whom i work - "preemptive optimization is the cause of most problems" (which is true for Rust in triplicate).
I think i found the issue - you're looking for the footer bytes at the end of the stream, but when the sender is ACK-less (we have this in a prod environment right now), you're reading two messages at a ttime and stripping start-end bytes from them, then re-encapsulating them so the actual listener sees two messages as the intermediate frame bytes exist in the middle.
Working on a rewrite of that search loop...

**Comment by wokket** [comment]
Hah, again I'm not all surprised to find bugs in here when you throw an actual workload at it for the first time.  This was the first real rust code I wrote!  I'm more than happy to help you get it right though!

Premature optimisation is absolutely an issue (but also half the fun of rust).  Given I didn't put a 'Not for Prod Use' warning on this one I'll take correct over fast and useless :)

I'm pretty sure a sender that doesn't wait for ACK's is in no way compliant with the spec, so that's _absolutely_ something I'd expect to see in prod 🤣

**Comment by wokket** [comment]
Confirmed that MLLP as a standard is synchronous and your prod sender is not a HL7 MLLP service:
![image](https://user-images.githubusercontent.com/3802829/127561258-aa803dda-7f46-413c-b197-58476ca47e56.png)

**Comment by sempervictus** [comment]
"This is healthcare..." might be what i get put on my tombstone. However, given the scarcity of architects/engineers in the field, pretty sure they'll keep me on life support in exchange for technical services until they bring the Borg online (accidentally of course, probably while moving to a new EHR).
#3  fixes this, and doesnt break synchronous ops either.
My code is actually ACK-less because they straight-up ignore them if sent :).

**Comment by wokket** [comment]
I'm away from the computer for the day shortly but I'll ponder how I want to play this.  Standards only work if everyone uses them (and the good thing is there's so many standards to choose from 😉 ), but I'm pragmatic above all else.

I don't want to encourage poor behaviour (I'd be returning ACK's even if the source system ignored them just so _my_ code was spec compliant), but yeah... prod...

**Comment by sempervictus** [comment]
If we want to be crowd pleasers, i guess we can pass an init param to the decoder like `aberrant` or something which would make it use the implementation of search in #3, or fall back to `compliant` when ACKs are honored - problem is that Rust doesnt have a way to set default values for those which requires breaking the API or possibly implementing a sister struct to do this with its own Impl and common code somehow shared by Type? (The Ruby DRY stuff informs a lot of my thinking to this day :) ). Byte scans are cheap though, its what people do with the data AFTER that gets expensive (i have to decompose weird message types for logical and time series back-ends, and commit into those uniquely, with each atomic op there costing tons more than this).
If we want to be l33t rustaceans however, we could probably find a faster way to match the bytes we're scanning for, skiplist them, or whatever, to keep the forward-scan semantic in #3 but get performance a bit closer to the speed of the (IMO) fragile original implementation.

**Comment by sempervictus** [comment]
So something like this maybe? https://rust-lang-nursery.github.io/futures-api-docs/0.1.27/futures/io/trait.AsyncSeek.html

**Comment by wokket** [comment]
The perf impact doesn't really bother me... it's easy to be fast if you can be wrong.

Like you I'd prefer not to clutter the API with this stuff... maybe a feature in the crate you opt in to??  `NotActuallyMLLP` or similar 🤣

**Comment by sempervictus** [comment]
Charming, love the name - i was thinking something a la `SomeoneDidntReadTheSpecImpl` but yeah, might be a good way to handle that

**Comment by wokket** [comment]
After a healthy ponder I've decided I _really_ don't want to make a crate named for a spec non spec-compliant by default, but am happy to make an opt-in feature for this stuff if we can make it work.  I'll merge the PR into a feature branch for now so I can look into crate features

**Comment by sempervictus** [comment]
Thank you, much appreciate it - if we could use a feature or pass a `sync` param a la `MllpDecoder::new(false)`, it would be of use as non-compliance and inconsistency are the only consistent things i've found in healthcare tech over the years :).
