### ISSUE TITLE
Ensure messages split accross TCP packets are handled correctly

### ISSUE THREAD

**Issue by wokket** [wokket/hl7-mllp-codec#4]
Per some [early feedback](https://www.reddit.com/r/rust/comments/dzxw9d/looking_for_feedback_on_hl7_mllp_crate/) on the crate we need to ensure that a message split over multiple TCP packets is handled correctly:

```
if I recall correctly, you need to handle the whole buffer in decode; so you need to buffer the data for later if there was no footer because next time it will be gone. Also, the footer might arrive in two parts when using TCP, but you're unlikely to observe TCP fragmentation when testing with localhost.
```

**Comment by sempervictus** [comment]
Non-issue AFAIK - we're dealing with a `TcpStream` object, not a packet-wise socket/FD.
It might be a problem if the `peekable()` `iter()` fails on EOF though, for which we probably just need a break+retry of the loop to pick up any new data in the stream context (im a bit hazy on how the inner part of a closure would deal with the expansion of the buffer over which it is iterating in a language as strict and static as Rust)

**Comment by wokket** [comment]
The fact we're given a stream doesn't change the fact it's packets under the hood.  Tokio (or similar) is getting packets over the wire, and sending them to us in bursts (the BytesMut buffer sent to each call to `decode`).  Whether it makes that call per-packet, or after an timeout following packet receipt (to bundle multiple packets received in quick succession) there's the opportunity for only part of a message to make it to `decode` in one call.

When I get a chance I might try and artificially send very small, very slow packets from a publisher of a large message and see what happens.

**Comment by sempervictus** [comment]
Interesting, so then we need to have the iterator fail gracefully on EOF when start bytes are found but no end bytes are present to retry the buffer as peekable iter after some delay, maybe progressive one (TCP socket timeouts will eventually be less than that).
